openapi: 3.0.0
info:
  title: Toy8 API Server
  version: 0.1.0
  description: To provide api endpoints as a service for our in-house mobile applications.
  contact:
    name: Fischer
    url: 'https://github.com/Lee-817'
    email: l.szeyu@toyeight.com
  termsOfService: ''
  license:
    name: placehodler
    url: 'https://github.com/Lee-817'
paths:
  /login:
    post:
      summary: Log in
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    x-stoplight:
                      id: zkh43pbv7a7ka
                  message:
                    type: string
                    x-stoplight:
                      id: nu2qhrxga42cu
                  token:
                    type: string
                    x-stoplight:
                      id: 0pmli87uoqsgh
              examples:
                Example 1:
                  value:
                    status: true
                    message: User Logged In Successfully
                    token: 2|OEhkDvEoDgxpwoVqd0Adql1OE2mYH4OOu8qLX4qu7cffe71d
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    x-stoplight:
                      id: 5ljd8fv9yjjp9
                  message:
                    type: string
                    x-stoplight:
                      id: zh6jtfnggfq38
              examples:
                Example 1:
                  value:
                    status: false
                    message: Email & Password does not match with our record.
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    x-stoplight:
                      id: ui4s57ae38cmt
                  errors:
                    type: object
                    x-stoplight:
                      id: emxi8esm3mt8r
              examples:
                Example 1:
                  value:
                    message: The password field is required.
                    errors:
                      password:
                        - The password field is required.
      operationId: post-login
      x-stoplight:
        id: khcvkdc0j8gto
      description: To login system and get bearer token.
      parameters:
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  x-stoplight:
                    id: h2n9xxn6z1ii8
                email:
                  type: string
                  x-stoplight:
                    id: 65j3nuu5cicty
            examples:
              Example 1:
                value:
                  password: good@night
                  email: moon_kindergarten@email.com
      security: []
  /logout:
    post:
      summary: Log out
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    x-stoplight:
                      id: 0mzuzs7huqywq
                  message:
                    type: string
                    x-stoplight:
                      id: widdzicmicolu
              examples:
                Example 1:
                  value:
                    status: true
                    message: Logged out success.
      operationId: post-logout
      x-stoplight:
        id: ixx93rgbjyupr
      description: 'To logout from the system, the associated bearer token will be deleted'
      parameters:
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
  /intervention/students:
    get:
      summary: Get student listing
      responses:
        2XX:
          description: Success
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    students:
                      - id: 4
                        user_type: child
                        first_name: Josh
                        last_name: Bobby
                        email: bobby@email.com
                        status: active
                        parent_user_id: null
                        kindergarten_user_id: 2
                        birth_date: null
                        phone_number: null
                        preferred_language_id: null
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 5
                        user_type: child
                        first_name: Otter
                        last_name: Taylor
                        email: taylor@email.com
                        status: active
                        parent_user_id: null
                        kindergarten_user_id: 2
                        birth_date: null
                        phone_number: null
                        preferred_language_id: null
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 6
                        user_type: child
                        first_name: Ruby
                        last_name: Chan
                        email: ruby@email.com
                        status: active
                        parent_user_id: null
                        kindergarten_user_id: 2
                        birth_date: null
                        phone_number: null
                        preferred_language_id: null
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                    pagination:
                      current_page: 1
                      last_page: 1
                properties:
                  students:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        user_type:
                          type: string
                        first_name:
                          type: string
                        last_name:
                          type: string
                        email:
                          type: string
                        status:
                          type: string
                        parent_user_id:
                          type: string
                          nullable: true
                        kindergarten_user_id:
                          type: integer
                        birth_date:
                          type: string
                          nullable: true
                        phone_number:
                          type: string
                          nullable: true
                        preferred_language_id:
                          type: integer
                          nullable: true
                        created_at:
                          type: string
                        updated_at:
                          type: string
                  pagination:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      last_page:
                        type: integer
              examples:
                Example 1:
                  value:
                    students:
                      - id: 4
                        user_type: child
                        first_name: Josh
                        last_name: Bobby
                        email: bobby@email.com
                        status: active
                        parent_user_id: null
                        kindergarten_user_id: 2
                        birth_date: null
                        phone_number: null
                        preferred_language_id: null
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 5
                        user_type: child
                        first_name: Otter
                        last_name: Taylor
                        email: taylor@email.com
                        status: active
                        parent_user_id: null
                        kindergarten_user_id: 2
                        birth_date: null
                        phone_number: null
                        preferred_language_id: null
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 6
                        user_type: child
                        first_name: Ruby
                        last_name: Chan
                        email: ruby@email.com
                        status: active
                        parent_user_id: null
                        kindergarten_user_id: 2
                        birth_date: null
                        phone_number: null
                        preferred_language_id: null
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                    pagination:
                      current_page: 1
                      last_page: 1
      operationId: get-intervention-students
      x-stoplight:
        id: 35dunisztch2k
      description: Retrive a list of students under your kindergarten account
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                  x-stoplight:
                    id: jga2p0cefqbt2
                '':
                  type: string
                  x-stoplight:
                    id: uxrfoezygnv38
            examples:
              Example 1:
                value:
                  page: 1
    parameters:
      - schema:
          type: string
        in: header
        name: Accept
        description: application/json
  /intervention/entries:
    get:
      summary: Get intervention active entries
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  entries:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        student_user_id:
                          type: integer
                        kindergarten_user_id:
                          type: integer
                        status:
                          type: string
                        created_at:
                          type: string
                        updated_at:
                          type: string
                  pagination:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      last_page:
                        type: integer
                x-examples:
                  Example 1:
                    entries:
                      - id: 1
                        student_user_id: 5
                        kindergarten_user_id: 2
                        status: active
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                    pagination:
                      current_page: 1
                      last_page: 1
              examples:
                Example 1:
                  value:
                    entries:
                      - id: 1
                        student_user_id: 5
                        kindergarten_user_id: 2
                        status: active
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                    pagination:
                      current_page: 1
                      last_page: 1
      operationId: get-intervention-entries
      x-stoplight:
        id: hjtitzird2cw2
      description: Retrive a list of active entries for each students.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                  x-stoplight:
                    id: 29ihnssxls1g9
            examples:
              Example 1:
                value:
                  page: 1
    parameters:
      - schema:
          type: string
        in: header
        name: Accept
        description: application/json
  /intervention/programs:
    get:
      summary: Get intervention program
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  programs:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        entry_id:
                          type: integer
                        student_user_id:
                          type: integer
                        kindergarten_user_id:
                          type: integer
                        start_date:
                          type: string
                        end_date:
                          type: string
                        status:
                          type: string
                        created_at:
                          type: string
                        updated_at:
                          type: string
                  pagination:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      last_page:
                        type: integer
                x-examples:
                  Example 1:
                    programs:
                      - id: 2
                        entry_id: 1
                        student_user_id: 5
                        kindergarten_user_id: 2
                        start_date: '2024-01-01'
                        end_date: '2024-06-30'
                        status: active
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 3
                        entry_id: 1
                        student_user_id: 6
                        kindergarten_user_id: 2
                        start_date: '2024-01-01'
                        end_date: '2024-06-30'
                        status: active
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                    pagination:
                      current_page: 1
                      last_page: 1
              examples:
                Example 1:
                  value:
                    programs:
                      - id: 2
                        entry_id: 1
                        student_user_id: 5
                        kindergarten_user_id: 2
                        start_date: '2024-01-01'
                        end_date: '2024-06-30'
                        status: active
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 3
                        entry_id: 1
                        student_user_id: 6
                        kindergarten_user_id: 2
                        start_date: '2024-01-01'
                        end_date: '2024-06-30'
                        status: active
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                    pagination:
                      current_page: 1
                      last_page: 1
      operationId: get-intervention-programs
      x-stoplight:
        id: cs2g2lamr7jbi
      description: Retrive a list of active programs for each students.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                student_id:
                  type: integer
              x-examples:
                Example 1:
                  page: 1
                  student_id: 5
            examples:
              Example 1:
                value:
                  page: 1
                  student_id: 5
  /intervention/modules:
    get:
      summary: Get intervention module
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    modules:
                      - id: 2
                        program_id: 2
                        kindergarten_user_id: 2
                        day_counter: 2
                        status: answering
                        finish_date: '2024-03-10'
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 3
                        program_id: 2
                        kindergarten_user_id: 2
                        day_counter: 360
                        status: pending
                        finish_date: null
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 4
                        program_id: 1
                        kindergarten_user_id: 2
                        day_counter: 360
                        status: pending
                        finish_date: null
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                    pagination:
                      current_page: 1
                      last_page: 1
                properties:
                  modules:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        program_id:
                          type: integer
                        kindergarten_user_id:
                          type: integer
                        day_counter:
                          type: integer
                        status:
                          type: string
                        finish_date:
                          type: string
                          nullable: true
                        created_at:
                          type: string
                        updated_at:
                          type: string
                  pagination:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      last_page:
                        type: integer
              examples:
                Example 1:
                  value:
                    modules:
                      - id: 2
                        program_id: 2
                        kindergarten_user_id: 2
                        day_counter: 2
                        status: answering
                        finish_date: '2024-03-10'
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 3
                        program_id: 2
                        kindergarten_user_id: 2
                        day_counter: 360
                        status: pending
                        finish_date: null
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 4
                        program_id: 1
                        kindergarten_user_id: 2
                        day_counter: 360
                        status: pending
                        finish_date: null
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                    pagination:
                      current_page: 1
                      last_page: 1
      operationId: get-intervention-modules
      x-stoplight:
        id: nxfi200zl0tz0
      description: Get module listing from specific program
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                program_id:
                  type: integer
                from_day:
                  type: integer
                to_day:
                  type: integer
              x-examples:
                Example 1:
                  program_id: 1
                  from_day: 1
                  to_day: 100
            examples:
              Example 1:
                value:
                  program_id: 1
                  from_day: 1
                  to_day: 100
    parameters:
      - schema:
          type: string
        in: header
        name: accept
        description: application/json
  '/intervention/modules/{module_id}':
    parameters:
      - schema:
          type: string
        name: module_id
        in: path
        required: true
    get:
      summary: Get module items from module id
      tags: []
      responses:
        2XX:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  module_items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        module_id:
                          type: integer
                        module_item_type:
                          type: string
                        language_id:
                          type: integer
                        order:
                          type: integer
                        remark:
                          type: string
                        created_at:
                          type: string
                        updated_at:
                          type: string
                  pagination:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      last_page:
                        type: integer
                x-examples:
                  Example 1:
                    module_items:
                      - id: 1
                        module_id: 2
                        module_item_type: intro
                        language_id: 1
                        order: 1
                        remark: This is a intro
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 2
                        module_id: 2
                        module_item_type: reward
                        language_id: 1
                        order: 2
                        remark: This is a reward
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 3
                        module_id: 2
                        module_item_type: activity
                        language_id: 1
                        order: 3
                        remark: This is an activity
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 4
                        module_id: 2
                        module_item_type: activity
                        language_id: 1
                        order: 4
                        remark: This is an activity
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 5
                        module_id: 2
                        module_item_type: activity
                        language_id: 1
                        order: 5
                        remark: This is an activity
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                    pagination:
                      current_page: 1
                      last_page: 1
              examples:
                Example 1:
                  value:
                    module_items:
                      - id: 1
                        module_id: 2
                        module_item_type: intro
                        language_id: 1
                        order: 1
                        remark: This is a intro
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 2
                        module_id: 2
                        module_item_type: reward
                        language_id: 1
                        order: 2
                        remark: This is a reward
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 3
                        module_id: 2
                        module_item_type: activity
                        language_id: 1
                        order: 3
                        remark: This is an activity
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 4
                        module_id: 2
                        module_item_type: activity
                        language_id: 1
                        order: 4
                        remark: This is an activity
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                      - id: 5
                        module_id: 2
                        module_item_type: activity
                        language_id: 1
                        order: 5
                        remark: This is an activity
                        created_at: '2024-04-17T01:11:17.000000Z'
                        updated_at: '2024-04-17T01:11:17.000000Z'
                    pagination:
                      current_page: 1
                      last_page: 1
      operationId: get-intervention-modules-module_id
      x-stoplight:
        id: ik92o9bg7750v
      description: Get a list of module items by provide specific module id
      parameters:
        - schema:
            type: integer
          in: query
          name: module_id
components:
  schemas:
    User:
      title: User
      x-stoplight:
        id: n7b9wskh2uceb
      type: object
      x-examples:
        Example 1:
          id: 5
          user_type: child
          first_name: Otter
          last_name: Taylor
          email: taylor@email.com
          status: active
          parent_user_id: null
          kindergarten_user_id: 2
          birth_date: null
          phone_number: null
          preferred_language_code: null
          created_at: '2024-03-11T20:18:44.000000Z'
          updated_at: '2024-03-11T20:18:44.000000Z'
      properties:
        id:
          type: integer
          x-stoplight:
            id: zes2pv5cf3q74
        user_type:
          type: integer
          x-stoplight:
            id: zbt8bzqmc4plp
        first_name:
          type: integer
          x-stoplight:
            id: 0z5y23bbrfg36
        last_name:
          type: string
          x-stoplight:
            id: mjbo8hit6cjkk
        email:
          type: string
          x-stoplight:
            id: rtdk1de77t0gu
        status:
          type: string
          x-stoplight:
            id: mu626b57zxr8a
        parent_user_id:
          type: string
          x-stoplight:
            id: q90jyysdagx7b
        kindergarten_user_id:
          type: string
          x-stoplight:
            id: etsupbs7uwhbf
        birth_date:
          type: string
          x-stoplight:
            id: 444r3l0r07knx
        phone_number:
          type: string
          x-stoplight:
            id: lutg4rmhy968j
        preferred_language_code:
          type: string
          x-stoplight:
            id: royngr353pqu3
        created_at:
          type: string
          x-stoplight:
            id: asiob18mul15l
        updated_at:
          type: string
          x-stoplight:
            id: nnnhvncwl090z
      description: ''
    Entry:
      type: object
      properties:
        id:
          type: integer
        student_user_id:
          type: integer
        kindergarten_user_id:
          type: integer
        status:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
      x-examples:
        Example 1:
          id: 1
          student_user_id: 5
          kindergarten_user_id: 2
          status: active
          created_at: '2024-04-17T01:11:17.000000Z'
          updated_at: '2024-04-17T01:11:17.000000Z'
    Program:
      type: object
      properties:
        id:
          type: integer
        entry_id:
          type: integer
        student_user_id:
          type: integer
        kindergarten_user_id:
          type: integer
        start_date:
          type: string
        end_date:
          type: string
        status:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
      x-examples:
        Example 1:
          id: 2
          entry_id: 1
          student_user_id: 5
          kindergarten_user_id: 2
          start_date: '2024-01-01'
          end_date: '2024-06-30'
          status: active
          created_at: '2024-04-17T01:11:17.000000Z'
          updated_at: '2024-04-17T01:11:17.000000Z'
    Module:
      type: object
      x-examples:
        Example 1:
          id: 4
          program_id: 1
          kindergarten_user_id: 2
          day_counter: 360
          status: pending
          finish_date: null
          created_at: '2024-04-17T01:11:17.000000Z'
          updated_at: '2024-04-17T01:11:17.000000Z'
      properties:
        id:
          type: integer
        program_id:
          type: integer
        kindergarten_user_id:
          type: integer
        day_counter:
          type: integer
        status:
          type: string
        finish_date:
          type: string
          nullable: true
        created_at:
          type: string
        updated_at:
          type: string
    Module-Items:
      type: object
      properties:
        id:
          type: integer
        module_id:
          type: integer
        module_item_type:
          type: string
        language_id:
          type: integer
        order:
          type: integer
        remark:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
      x-examples:
        Example 1:
          id: 1
          module_id: 2
          module_item_type: intro
          language_id: 1
          order: 1
          remark: This is a intro
          created_at: '2024-04-17T01:11:17.000000Z'
          updated_at: '2024-04-17T01:11:17.000000Z'
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
  requestBodies: {}
servers:
  - url: 'http://localhost:8080/api'
    description: Development
  - url: 'http://localhost:8080/api/#'
    description: Staging
  - url: 'http://localhost:8080/api/#'
    description: Production
tags:
  - name: Toy8 API Server
    description: OpenAPI documentation
security:
  - Authorization: []
